### ISSUE TITLE
Mods aren't automatically updated on manifest change

### ISSUE THREAD

**Issue by NobodyMiner** [kukiteam/ts-kukilauncher#6]
- [ ] Implement Manifest Version

**Comment by Sascha-T** [comment]
If you think what im thinking, our options are:
 - Websockets:
   Pros: Work immediatly, work reliably
   Cons: Require another open port + Meddling with Certificates.
 - Latest Commit Hash
   Pros: Doesn't require another port, Comes directly from Github
   Cons: Don't see any

I think we should use the Commit SHA.
The launcher should check every 30 minutes for a new update + on startup + on shutdown + on closing game + on starting game (halts the starting of the game until update check complete)

Please make a notification when there's a new update

**Comment by Anoobarmy** [comment]
> If you think what im thinking, our options are:
> 
> * Websockets:
>   Pros: Work immediatly, work reliably
>   Cons: Require another open port + Meddling with Certificates.
> * Latest Commit Hash
>   Pros: Doesn't require another port, Comes directly from Github
>   Cons: Don't see any
> 
> I think we should use the Commit SHA.
> The launcher should check every 30 minutes for a new update + on startup + on shutdown + on closing game + on starting game (halts the starting of the game until update check complete)
> 
> Please make a notification when there's a new update

 what if the update fails (github down or something of that sort) and it gets stuck on update? would the game just get stuck and not start? we should probably implement some sort of timeout ( well you becouse i've got no idea of how to do this) just in case it gets stuck, or maybe a connection check or something like that.

**Comment by NobodyMiner** [comment]
You're not exactly understanding what I mean... I want to know, If the Version manifest at https://github.com/kukiteam/kukicraft/blob/master/manifest.json is updated, which is why I added the field version. This field will be compared to the field in the local file to determine if the mods need to be updated.

I think what you mean are Launcher versions, which are also important, but are secondary at the moment. #9

**Comment by NobodyMiner** [comment]
> what if the update fails (github down or something of that sort) and it gets stuck on update? would the game just get stuck and not start? we should probably implement some sort of timeout ( well you becouse i've got no idea of how to do this) just in case it gets stuck, or maybe a connection check or something like that.

I think you are not understanding the problem.

**Comment by NobodyMiner** [comment]
Fixed in e6b5881e1afc455aea71657604be7c1e6137db67
